# Generated by Django 5.1.7 on 2025-06-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250608_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
