# Generated by Django 5.1.7 on 2025-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hobbies',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
